apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cast_service_deployment.name }}  
  labels:
    app: {{ .Values.cast_service_deployment.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.cast_service_deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.cast_service_deployment.app }}
    spec:
      initContainers:
      - name: {{ .Values.cast_service_deployment.initContainersName }}
        image: {{ .Values.cast_service_deployment.initContainersImage }}
        command: ['sh', '-c', 
          'until pg_isready -h cast-db -p 5432; 
          do echo waiting for database; sleep 2; done;']
      containers:
      - name: {{ .Values.cast_service_deployment.containersName }}
        image: {{ .Values.cast_service_deployment.containersImage }}
        command: ["uvicorn"]
        args: ["app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
        env:
        - name: {{ .Values.cast_service_deployment.envName }}
          value: {{ .Values.cast_service_deployment.envValue }}
        ports:
        - containerPort: {{ .Values.cast_service_deployment.containerPort }}
          protocol: {{ .Values.cast_service_deployment.protocol }}
      restartPolicy: {{ .Values.cast_service_deployment.restartPolicy }}
