apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cast_service_service.name }}
spec:
  ports:
    - name: {{ .Values.cast_service_service.portName }}
      port: {{ .Values.cast_service_service.port }}
      targetPort: {{ .Values.cast_service_service.targetPort }}
  selector:
    app: {{ .Values.cast_service_service.app }}