apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.movie_service_service.name }}
spec:
  ports:
    - name: {{ .Values.movie_service_service.namePort }}
      port: {{ .Values.movie_service_service.port }}
      targetPort: {{ .Values.movie_service_service.targetPort }}
  selector:
    app: {{ .Values.movie_service_service.app }}