apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres_data_cast_persistentvolumeclaim.name }}
spec:
  accessModes:
    - {{ .Values.postgres_data_cast_persistentvolumeclaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.postgres_data_cast_persistentvolumeclaim.storage }}
