apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: vikinghacker/cast-app:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: cast-config
