apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  labels:
    app: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      initContainers:
      - name: check-db-ready
        image: postgres:12.1-alpine
        command: ['sh', '-c', 
          'until pg_isready -h cast-db -p 5432; 
          do echo waiting for database; sleep 2; done;']
      containers:
      - name: cast-service
        image: vikinghacker/cast-app:latest
        command: ["uvicorn"]
        args: ["app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
        env:
        - name: DATABASE_URI
          value: postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev
        ports:
        - containerPort: 8000
          protocol: TCP
      restartPolicy: Always
