apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-service
  template:
    metadata:
      labels:
        app: movies-service
    spec:
      containers:
        - name: movie-service
          image: vikinghacker/movie-app:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: movie-config