apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movies-api
  template:
    metadata:
      labels:
        app: movies-api
    spec:
      containers:
        - name: movie-service
          image: vikinghacker/movie-app:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: movie-config