apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 8080;

      location / {
        default_type text/html;
        return 200 '
        <!DOCTYPE html>
        <html>
        <head><title>Welcome</title></head>
        <body>
          <h1>Welcome to our API</h1>
          <p><a href="/api/v1/movies/docs">Movies API Documentation</a></p>
          <p><a href="/api/v1/casts/docs">Casts API Documentation</a></p>
        </body>
        </html>
        ';
      }

      location /api/v1/movies {
        proxy_pass http://movie-service:8001;
      }

      location /api/v1/casts {
        proxy_pass http://cast-service:8002;
      }
    }
