apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-movie
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/postgres_data_movie"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-cast
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/postgres_data_cast"
