apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx_service.name }}
spec:
  ports:
    - name: {{ .Values.nginx_service.namePort }}
      port: {{ .Values.nginx_service.port }}
      targetPort: {{ .Values.nginx_service.targerPort }}
  selector:
    app: {{ .Values.nginx_service.app }}
